---
services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - ${HS_PATH}/minecraft/data:/data

volumes:
  minecraft_data:
    name: "minecraft_data"

networks:
  default:
    name: hs-bridge
    driver: bridge